import Link from 'next/link';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {Photo,TextLink} from '@/components/editorial';
import {Reveal} from '@/components/motion';
export default function Home(){return <>
<section className="cinema-hero"><Photo name="portrait" alt="Dr. Sudhir Srivastava seated in a black formal jacket" priority/><div className="hero-content wrap"><p className="eyebrow">SURGEON. INNOVATOR. MENTOR.</p><h1>Dr. Sudhir<br/>Srivastava</h1><p className="hero-degree">SUDHIR PREM SRIVASTAVA, M.D.</p><p className="hero-line">A life in surgery.<br/>A vision beyond boundaries.</p><div className="actions"><Link href="/journey" className="button light">His journey <ArrowUpRight size={18}/></Link><Link href="/journey#cv" className="text-link">View CV</Link></div></div><div className="hero-bottom wrap"><span>CARDIOTHORACIC SURGERY & SURGICAL ROBOTICS</span><a href="#purpose">Scroll down <ArrowDown size={16}/></a></div></section>
<section id="purpose" className="purpose wrap"><Reveal><p className="eyebrow">THE PURPOSE BEHIND THE PRACTICE</p></Reveal><Reveal><h2>Advanced surgery.<br/><em>Within greater reach.</em></h2><div className="purpose-body"><p>From beating-heart bypass to surgical robotics, Dr. Srivastava’s work is guided by a conviction: access to advanced care should not depend on geography or cost.</p><TextLink href="/journey">Meet the person behind the vision</TextLink></div></Reveal></section>
<section className="work-stories wrap"><div className="section-heading"><div><p className="eyebrow">ONE LIFE. CONNECTED PURSUITS.</p><h2>Where experience<br/>becomes possibility.</h2></div></div><div className="story-grid">{[{n:'01',title:'The surgeon.',image:'surgeon',alt:'Dr. Srivastava at work in surgical attire',text:'Exploring new approaches to beating-heart and robotic cardiac surgery.',href:'/legacy',action:'Surgical legacy'},{n:'02',title:'The innovator.',image:'mantra',alt:'SSI Mantra surgical robotic system',text:'Bringing the perspective of a surgeon to the development of SSI Mantra.',href:'/legacy#innovation',action:'The Mantra story'},{n:'03',title:'The mentor.',image:'mentor',alt:'Dr. Srivastava in discussion with colleagues',text:'Sharing techniques, building programs and helping surgical teams grow.',href:'/academic',action:'Knowledge & recognition'}].map(x=><Reveal key={x.n}><Link className="story" href={x.href}><Photo name={x.image} alt={x.alt}/><div className="story-top"><span/><ArrowUpRight size={24}/></div><div className="story-caption"><h3>{x.title}</h3><p>{x.text}</p><span className="story-action">{x.action} <ArrowUpRight size={16}/></span></div></Link></Reveal>)}</div></section>
<section className="mantra-feature"><div className="wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">SURGICAL EXPERIENCE, ENGINEERED</p><h2>The man<br/>behind <em>Mantra.</em></h2></div><div className="feature-aside"><p>What if advanced surgical technology could reach more operating rooms?</p><TextLink href="/legacy#innovation">Read about SSI Mantra</TextLink></div></div></Reveal><Photo name="mantra-wide" alt="SSI Mantra robotic arms and surgical system"/><div className="feature-foot"><span>SSI MANTRA SURGICAL ROBOTIC SYSTEM</span><p>A development journey led by Dr. Srivastava and brought to life by the SS Innovations team.</p></div></div></section>
<section className="borderless wrap"><Reveal><span className="eyebrow">TELESURGERY</span><h2>Expertise travels.<br/><em>Possibility expands.</em></h2><p>From Gurgaon to Jaipur. From Strasbourg to Indore. Dr. Srivastava’s telesurgical work explores how surgical expertise can cross distances.</p><TextLink href="/legacy#telesurgery">How telesurgery works</TextLink></Reveal><Reveal><Photo name="console" alt="Dr. Srivastava at a surgical console with an operating-room team"/><p className="image-caption">At the console, with the surgical team.</p></Reveal></section>
<section className="mentor-feature"><Photo name="speaker" alt="Dr. Srivastava speaking at a lectern"/><div><span className="eyebrow">EXPERIENCE, SHARED</span><h2>The next chapter<br/>belongs to<br/><em>more hands.</em></h2><p>Through teaching, live surgery and research, knowledge moves from one surgeon to the next.</p><TextLink href="/academic">Teaching & research</TextLink></div></section>
<section className="wrap section-space"><div className="chapter-heading"><p className="eyebrow">SSICRS</p><div><h2>Building capability<br/><em>beyond the operating room.</em></h2><p>Through SSICRS, structured education brings surgeons, nurses and technicians together around the complete workflow of robotic surgery.</p><TextLink href="/associations#ssicrs">About SSICRS</TextLink></div></div></section></>}
