'use client';
import {useMemo,useState} from 'react';
import entries from '@/data/academic.json';

import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
const all=entries.filter(e=>!['Professional service','Awards & honours'].includes(e.category)).sort((a,b)=>(Number(b.year)||0)-(Number(a.year)||0));
const categories=['All work','Publications','Research','Scientific presentations','Live surgical presentations','Posters','Invited lectures'];
export default function AcademicArchive(){const[q,setQ]=useState('');const[category,setCategory]=useState('All work');const[year,setYear]=useState('All years');const years=useMemo(()=>Array.from(new Set(all.map(e=>e.year).filter(Boolean))).sort().reverse(),[]);const filtered=all.filter(e=>(category==='All work'||e.category===category)&&(year==='All years'||e.year===year)&&e.text.toLocaleLowerCase().includes(q.toLocaleLowerCase()));return <section className="archive"><div className="section-heading"><div><span className="eyebrow">PUBLICATIONS & PRESENTATIONS</span><h2>Search the collection.</h2></div></div><div className="archive-toolbar"><label className="search-field" htmlFor="archive-search">SEARCH<input id="archive-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Try a title, author or topic…"/></label><label className="year-field" htmlFor="archive-year">YEAR<NativeSelect id="archive-year" value={year} onChange={e=>setYear(e.target.value)}><NativeSelectOption>All years</NativeSelectOption>{years.map(y=><NativeSelectOption key={y}>{y}</NativeSelectOption>)}</NativeSelect></label>{(q||year!=='All years'||category!=='All work')&&<button className="button outline" onClick={()=>{setQ('');setYear('All years');setCategory('All work')}}>Reset filters</button>}</div><div className="filter-list" aria-label="Filter academic record by category">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="results-label" role="status">{filtered.length} {filtered.length===1?'entry':'entries'}{category!=='All work'?` · ${category}`:''}</p><div>{filtered.map(e=><article className="academic-row" key={e.id}><span className="year">{e.year||'Undated'}</span><div><div className="category">{e.category}</div><p>{e.text}</p>{'url' in e&&typeof e.url==='string'&&<a href={e.url} target="_blank" rel="noopener noreferrer" className="text-link">Read the publication ↗</a>}</div></article>)}</div>{!filtered.length&&<Empty className="empty-state"><EmptyTitle>No matching entries</EmptyTitle><EmptyDescription>Try another topic, category or year.</EmptyDescription><button className="button outline" onClick={()=>{setQ('');setYear('All years');setCategory('All work')}}>Show all entries</button></Empty>}</section>}
