'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Menu,X,Download} from 'lucide-react';
import {ScrollProgress} from './motion';
export const navigation=[['/','Home'],['/journey','Journey'],['/legacy','Surgery & Innovation'],['/associations','Associations'],['/academic','Ideas & Recognition'],['/media','Media']];
export function Header(){const path=usePathname().replace(/\/$/,'')||'/';const[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[path]);return <header className={`site-header ${path==='/'?'over-hero':''}`}><Link href="/" className="wordmark" aria-label="Dr. Sudhir Srivastava home"><span className="monogram">SS</span><span>DR. SUDHIR<br/>SRIVASTAVA</span></Link><button className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="main-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="main-navigation" aria-label="Main navigation" className={open?'main-nav is-open':'main-nav'} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);document.querySelector<HTMLButtonElement>('.menu-toggle')?.focus()}}}>{navigation.map(([href,label])=><Link key={href} href={href} aria-current={(path===href||(href!=='/'&&path.startsWith(href+'/')))?'page':undefined} onClick={()=>setOpen(false)}>{label}</Link>)}</nav><ScrollProgress/></header>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><p className="eyebrow">A LIFE IN SURGERY. A VISION BEYOND.</p><h2>Dr. Sudhir<br/>Srivastava</h2></div><div className="footer-links"><nav aria-label="Footer navigation">{navigation.slice(1).map(([href,label])=><Link key={href} href={href}>{label}<ArrowUpRight size={16}/></Link>)}</nav><a href="/documents/Dr-Sudhir-Srivastava-CV.pdf" download className="text-link">Download CV <Download size={16}/></a></div></div><div className="footer-bottom"><span>Sudhir Prem Srivastava, M.D.</span><span>Surgeon · Innovator · Mentor</span><a href="#main">Back to top ↑</a></div></div></footer>}
export function CVButton(){return <a className="button dark" href="/documents/Dr-Sudhir-Srivastava-CV.pdf" download>Download CV <Download size={17}/></a>}
export function PrintButton(){return <button className="button outline" onClick={()=>window.print()}>Print this page</button>}
