'use client';
import {useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ArrowLeft,ArrowRight,ArrowUpRight} from 'lucide-react';
import {Photo} from '@/components/editorial';
import {telesurgery} from '@/data/stories';
import type {PublicInnovation} from '@/data/innovations';
export function TechnologyExplorer({items}:{items:PublicInnovation[]}){const[active,setActive]=useState(items[0].id);const startX=useRef<number|null>(null);const index=items.findIndex(p=>p.id===active);function step(d:number){setActive(items[(index+d+items.length)%items.length].id)}return <Tabs value={active} onValueChange={setActive} className="technology-tabs"><TabsList className="story-tabs" aria-label="Explore technologies">{items.map(p=><TabsTrigger key={p.id} value={p.id} onFocus={e=>e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'})}>{p.name}</TabsTrigger>)}</TabsList>{items.map(p=><TabsContent key={p.id} value={p.id} className={`technology-panel ${p.image?'':'text-innovation'}`} onTouchStart={e=>{startX.current=e.touches[0].clientX}} onTouchEnd={e=>{if(startX.current!==null){const dx=e.changedTouches[0].clientX-startX.current;if(Math.abs(dx)>60)step(dx<0?1:-1);startX.current=null}}}>{p.image?<Photo name={p.image} alt={p.altText}/>:<div className="innovation-wordmark" aria-hidden="true"><span>{String(p.displayOrder).padStart(2,'0')}</span><strong>{p.name}</strong></div>}<div><p className="eyebrow">{p.category}</p><h3>{p.shortDescription}</h3><p>{p.detailedDescription}</p>{p.status&&<span className="innovation-status">{p.status}</span>}{p.technicalDetails.length>0&&<details><summary>Technical details</summary><ul>{p.technicalDetails.map(d=><li key={d}>{d}</li>)}</ul></details>}</div></TabsContent>)}<div className="milestone-controls"><button className="button outline" onClick={()=>step(-1)}><ArrowLeft size={18}/>Previous</button><span aria-live="polite">{index+1} / {items.length}</span><button className="button outline" onClick={()=>step(1)}>Next<ArrowRight size={18}/></button></div></Tabs>}
export function TelesurgeryExplorer(){const[active,setActive]=useState('0');const index=Number(active);return <Tabs value={active} onValueChange={setActive} className="telesurgery-tabs"><TabsList className="story-tabs" aria-label="Telesurgery milestones">{telesurgery.map((p,i)=><TabsTrigger key={p.date} value={String(i)} onFocus={e=>e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'})}>{p.date}</TabsTrigger>)}</TabsList>{telesurgery.map((p,i)=><TabsContent key={p.date} value={String(i)} className="telesurgery-panel"><div className="connection"><span>{p.from}</span><ArrowRight aria-label="to"/><span>{p.to}</span></div><div className="connection-detail"><span className="quiet-number">{String(i+1).padStart(2,'0')} / {String(telesurgery.length).padStart(2,'0')}</span><div><h3>{p.title}</h3><p>{p.text}</p>{(p.distance||p.latency||p.specialty)&&<dl className="milestone-facts">{[['Distance',p.distance],['Latency',p.latency],['Specialty',p.specialty]].map(([label,value])=>value&&<div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{p.url&&<a className="text-link" href={p.url} target="_blank" rel="noopener noreferrer">Read the announcement <ArrowUpRight size={17}/></a>}</div></div></TabsContent>)}<div className="milestone-controls"><button className="button outline" disabled={index===0} onClick={()=>setActive(String(index-1))}><ArrowLeft size={18}/>Previous</button><span aria-live="polite">{index+1} of {telesurgery.length}</span><button className="button outline" disabled={index===telesurgery.length-1} onClick={()=>setActive(String(index+1))}>Next<ArrowRight size={18}/></button></div></Tabs>}
